### ISSUE TITLE
Adafruit ESP32-S2 TFT Feather - 4MB Flash, 2MB PSRAM, STEMMA QT

### ISSUE THREAD

**Issue by indymx** [adafruit/Adafruit_TestBed#5]
With this device, the I2C scan produces no results with a SHT40 connected to the STEMMA QT connector. I can blink an external LED like crazy, but no other devices can be seen. Any Ideas? 
(https://www.adafruit.com/product/5300)

**Comment by ladyada** [comment]
please try the latest version just commited!
https://github.com/adafruit/Adafruit_TestBed/blob/master/examples/I2C_Scan/I2C_Scan.ino
